[project]
name = "dobermann"
version = "0.1.0"
description = "Modern python library for discourse segmentation."
readme = "README.md"
authors = [
    { name = "Paddy Denier", email = "202327146+paddydenier@users.noreply.github.com" }
]
requires-python = ">=3.12"

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Text Processing :: Linguistic",
]

dependencies = [
    "spacy>=3.8.14",
    "nltk>=3.9.4",
    "sentence-transformers>=5.4.1",
]

[project.scripts]
dobermann = "dobermann:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
]

docs = [
    "sphinx>=9.1.0",
]
