[project]
name = "dobermann"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paddy Denier", email = "202327146+paddydenier@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "spacy>=3.8.14",
    "en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
    "nltk>=3.9.4",
    "sentence-transformers>=5.4.1",
]

[project.scripts]
dobermann = "dobermann:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
    "sphinx>=9.1.0",
]
